name = "SoftSol3D"
uuid = "076d1e86-833d-4ad2-a182-b950c70137f2"
authors = ["harold-berjamin <92039688+harold-berjamin@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
